# Generated by Django 4.2.11 on 2025-04-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FodderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FodderListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specific_location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fodder_marketplace.county')),
                ('fodder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fodder_marketplace.foddertype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fodder_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FodderInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('interested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fodder_interests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='fodder_marketplace.fodderlisting')),
            ],
        ),
        migrations.CreateModel(
            name='FodderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fodder_images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fodder_marketplace.fodderlisting')),
            ],
        ),
        migrations.CreateModel(
            name='FodderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fodder_marketplace.county')),
                ('fodder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fodder_marketplace.foddertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fodder_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
