# Generated by Django 4.2.11 on 2025-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodder_marketplace', '0002_alter_fodderlisting_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fodderlisting',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
