# Generated by Django 4.2.11 on 2025-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodder_marketplace', '0003_alter_fodderlisting_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fodderlisting',
            name='unit',
            field=models.CharField(choices=[('bales', 'Bales'), ('kg', 'Kilograms'), ('tons', 'Tons'), ('bags', 'Bags'), ('liters', 'Liters'), ('pieces', 'Pieces')], default='kg', max_length=50),
        ),
    ]
