# Generated by Django 4.2.11 on 2025-04-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodder_marketplace', '0004_alter_fodderlisting_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fodderimage',
            name='image',
            field=models.ImageField(upload_to='fodder_images/%Y/%m/%d/'),
        ),
    ]
